version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: hello_docker-postgres
    environment:
      POSTGRES_DB: hello_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    networks:
      - hello-net

  java-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: volumes-java-server
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/hello_db
      DB_USER: user
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - hello-net
    volumes:
      - ./server/src:/app/src   # bind mount исходников для live-изменений

  java-client:
    stdin_open: true   # -i
    tty: true          # -t
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: volumes-java-client
    depends_on:
      - java-server
    networks:
      - hello-net
    volumes:
      - ./client/src:/app/src   # bind mount исходников клиента

networks:
  hello-net:
    driver: bridge

volumes:
  pgdata:
